{{- $dc := .Values.datacube }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "datacube-data.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "datacube-data.name" . }}
    helm.sh/chart: {{ include "datacube-data.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "datacube-data.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "datacube-data.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
      {{- range $key, $value := .Values.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
      # Turning single-request-reopen option on would fix issue where in two requests from the same port are
      # not handled correctly it will close the socket and open a new one before sending the second request.
      dnsConfig:
        options:
          - name: single-request-reopen
      # Copy over WMS config from container image during init
      initContainers:
{{- if .Values.wmsConfig.image }}
      - name: wms-config
        image: "{{ $.Values.wmsConfig.image.repository }}:{{ $.Values.wmsConfig.image.tag }}"
        imagePullPolicy: {{ $.Values.wmsConfig.image.pullPolicy }}
        args: [ "cp", "-f", "{{ .Values.wmsConfig.image.src }}", "{{ .Values.wmsConfig.path }}/{{ .Values.wmsConfig.filename }}" ]
        volumeMounts:
        - mountPath: {{ .Values.wmsConfig.path }}
          name: wms-config-volume
{{- if .Values.wmsConfig.subpath }}
          subPath: {{ .Values.wmsConfig.subpath }}
{{- end }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ {{- range .Values.dockerArgs }} {{ . | quote }}, {{ end -}} ]
          env:
          - name: AWS_DEFAULT_REGION
            value: {{ .Values.aws_region }}
          - name: SQS_QUEUE_NAME
            value: {{ .Values.sqs_queue_name }}
          # Merge config URL for download or local file mounted via volume  
{{- if .Values.wmsConfig.url }}
          - name: WMS_CONFIG_URL
            value: {{ .Values.wmsConfig.url | quote }}
{{- end }}
{{- if or .Values.wmsConfig.configMap .Values.wmsConfig.image }}
          - value: "{{ .Values.wmsConfig.path }}/{{ .Values.wmsConfig.filename }}"
            name: WMS_CONFIG_PATH
{{- end }}
          - name: DB_HOSTNAME
            value: {{ .Values.database.host | quote }}
          - name: DB_PORT
            value: {{ .Values.database.port | quote }}
          - name: DB_DATABASE
            value: {{ .Values.database.database | quote }}
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.database.existingSecret }}
                key: postgres-username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.database.existingSecret }}
                key: postgres-password
          - name: DATACUBE_CONFIG_PATH
            value: {{ $dc.configPath }}
{{- if .Values.additionalEnvironmentVars }}
{{- range $arg, $value := .Values.additionalEnvironmentVars }}
          - name: {{ $arg | quote }}
            value: {{ $value | quote }}
{{- end }}
{{- end }}
          # Mount the config volume
          volumeMounts:
{{- if or .Values.wmsConfig.configMap .Values.wmsConfig.image }}
            - mountPath: {{ .Values.wmsConfig.path }}
              name: wms-config-volume
{{- end }}           
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
      # Define the config volume
      volumes:
{{- if or .Values.wmsConfig.configMap .Values.wmsConfig.image }}
      - name: wms-config-volume
{{- if .Values.wmsConfig.configMap }}
        configMap:
          name: {{ .Values.wmsConfig.configMap }}
{{- else if .Values.wmsConfig.image }}
        emptyDir: {}      
    {{- with .Values.tolerations }}
{{- end }}
{{- end }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
