{{- if .Values.wms.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
{{- $dc := .Values.datacube }}
{{- $image := .Values.image }}
{{- $prometheus := .Values.prometheus }}
{{- $profiling := .Values.profiling }}
{{- $pyspy := .Values.pyspy }}
metadata:
  name: "{{ template "datacube.fullname" . }}-{{ .Values.clusterInfo.envName }}"
  labels:
    app: {{ template "datacube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if not .Values.wms.autoscaling }}
  replicas: {{ .Values.minReplicas }}
{{- end }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.wms.maxSurge | quote }}
      maxUnavailable: {{ .Values.wms.maxUnavailable | quote }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "datacube.name" . }}
        release: {{ .Release.Name }}
      annotations:
{{ toYaml .Values.wms.annotations | indent 8 }}
    spec:
      # Turning single-request-reopen option on would fix issue where in two requests from the same port are
      # not handled correctly it will close the socket and open a new one before sending the second request.
      dnsConfig:
        options:
        - name: single-request-reopen
      initContainers:
{{- if .Values.wmsConfig.image }}
      - name: wms-config
        image: "{{ $.Values.wmsConfig.image.repository }}:{{ $.Values.wmsConfig.image.tag }}"
        imagePullPolicy: {{ $.Values.wmsConfig.image.pullPolicy }}
        args: [ "cp", "-f", "{{ .Values.wmsConfig.image.src }}", "{{ .Values.wmsConfig.path }}/{{ .Values.wmsConfig.filename }}" ]
        volumeMounts:
        - mountPath: {{ .Values.wmsConfig.path }}
          name: wms-config-volume
{{- if .Values.wmsConfig.subpath }}
          subPath: {{ .Values.wmsConfig.subpath }}
{{- end }}
{{- end }}
      containers:
{{- if $pyspy.enabled }}
      - name: pyspy
        image: "{{ $.Values.pyspy.image.repository }}:{{ $.Values.pyspy.image.tag }}"
        imagePullPolicy: {{ $.Values.pyspy.image.pullPolicy }}
        args: {}
        volumeMounts:
        - mountPath: {{ .Values.pyspy.path }}
          name: pyspy-volume
      SecurityContext:
        capabilities:
          add:
          - SYS_PTRACE
{{- end }}
      - name: wms
        env:
{{- if .Values.wmsConfig.url }}
        - name: WMS_CONFIG_URL
          value: {{ .Values.wmsConfig.url | quote }}
{{- end }}
{{- if or .Values.wmsConfig.configMap .Values.wmsConfig.image }}
        - value: "{{ .Values.wmsConfig.path }}/{{ .Values.wmsConfig.filename }}"
          name: WMS_CONFIG_PATH
{{- end }}
        - name: DB_HOSTNAME
          value: {{ .Values.database.host | quote }}
        - name: DB_PORT
          value: {{ .Values.database.port | quote }}
        - name: DB_DATABASE
          value: {{ .Values.database.database | quote }}
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ template "datacube.secretName" . }}
              key: postgres-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "datacube.secretName" . }}
              key: postgres-password
        - name: VIRTUAL_HOST
          value: localhost,127.0.0.
        - name: DATACUBE_CONFIG_PATH
          value: {{ $dc.configPath }}
{{- if $prometheus.enabled }}
        - name: prometheus_multiproc_dir
          value: {{ $prometheus.path | quote }}
{{- end }}
{{- if $profiling.enabled }}
        - name: PROFILER_FILE_PATH
          value: {{ $profiling.path }}
        - name: PROFILER
          value: {{ 1 | quote }}
{{- end }}
{{- if .Values.wms.awsCredentialsSecret }}
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: {{ .Values.wms.awsCredentialsSecret }}
              key: AWS_DEFAULT_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.wms.awsCredentialsSecret }}
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.wms.awsCredentialsSecret }}
              key: AWS_SECRET_ACCESS_KEY
{{- end }}
{{- if .Values.wms.additionalEnvironmentVars }}
{{- range $arg, $value := .Values.wms.additionalEnvironmentVars }}
        - name: {{ $arg | quote }}
          value: {{ $value | quote }}
{{- end }}
{{- end }}
        image: "{{ $image.repository }}:{{ $image.tag }}"
        imagePullPolicy: {{ $image.pullPolicy }}
        ports:
        - containerPort: 8000
        resources:
{{ toYaml .Values.wms.resources | indent 10 }}
        {{- with .Values.wms.livenessProbe }}
        livenessProbe:
{{ toYaml . | indent 10 }}
        {{- end }}
        {{- with .Values.wms.readinessProbe }}
        readinessProbe:
{{ toYaml . | indent 10 }}
        {{- end }}
        args: [ {{- range .Values.wms.dockerArgs }} {{ . | quote }}, {{ end -}} ]
        terminationGracePeriodSeconds: 60
        volumeMounts:
{{- if $prometheus.enabled }}
        - mountPath: {{ $prometheus.path }}
          name: prometheus-volume
{{- end }}
{{- if $profiling.enabled }}
        - mountPath: {{ $profiling.path }}
          name: profiling-volume
{{- end }}
{{- if $pyspy.enabled }}
        - mountPath: {{ $pyspy.path }}
          name: pyspy-volume
{{- end }}
{{- if or .Values.wmsConfig.configMap .Values.wmsConfig.image }}
        - mountPath: {{ .Values.wmsConfig.path }}
          name: wms-config-volume
{{- end }}
      restartPolicy: Always
{{- if $pyspy.enabled }}
      SecurityContext:
        capabilities:
          add:
          - SYS_PTRACE
{{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
{{- if $prometheus.enabled }}
      - name: prometheus-volume
        emptyDir: {}
{{- end }}
{{- if $profiling.enabled }}
      - name: profiling-volume
        emptyDir: {}
{{- end }}
{{- if or .Values.wmsConfig.configMap .Values.wmsConfig.image }}
      - name: wms-config-volume
{{- if .Values.wmsConfig.configMap }}
        configMap:
          name: {{ .Values.wmsConfig.configMap }}
{{- else if .Values.wmsConfig.image }}
        emptyDir: {}
{{- end }}
{{- end }}
status: {}
{{- end }}
